kind: pipeline
type: kubernetes
name: build-arm64
platform:
  arch: arm64
  os: linux
node_selector:
  kubernetes.io/arch: arm64
tolerations:
- key: arch
  operator: Equal
  value: arm64
  effect: NoSchedule
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: harbor.k-space.ee/${DRONE_REPO}
    tags: latest-arm64
    registry: harbor.k-space.ee
    squash: true
    experimental: true
    mtu: 1300
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
type: kubernetes
name: build-amd64
platform:
  arch: amd64
  os: linux
node_selector:
  kubernetes.io/arch: amd64
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: harbor.k-space.ee/${DRONE_REPO}
    tags: latest-amd64
    registry: harbor.k-space.ee
    squash: true
    experimental: true
    mtu: 1300
    storage_driver: vfs
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
type: kubernetes
name: manifest
steps:
- name: manifest
  image: plugins/manifest
  settings:
    target: harbor.k-space.ee/${DRONE_REPO}:latest
    template: harbor.k-space.ee/${DRONE_REPO}:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
depends_on:
- build-amd64
- build-arm64
